package ljj.mapper;

import ljj.mapper.TContent;
import org.springframework.stereotype.Repository;

@Repository(value="TContentMapper")
public interface TContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    int insert(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    int insertSelective(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    TContent selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    int updateByPrimaryKeySelective(TContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Thu Sep 28 14:00:51 CST 2017
     */
    int updateByPrimaryKey(TContent record);
}