package ljj.mapper;


import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TShowcontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    int insert(TShowcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    int insertSelective(TShowcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    TShowcontent selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    int updateByPrimaryKeySelective(TShowcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_showcontent
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    int updateByPrimaryKey(TShowcontent record);

    List<TShowcontent> getRsList();

    int saveOrUpdate(@Param("list") List<TShowcontent> list);

}