package ljj.mapper;

import java.util.Date;

public class TShowcontent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_showcontent.c_id
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_showcontent.c_person
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    private String cPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_showcontent.c_mz
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    private String cMz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_showcontent.d_showtime
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    private Date dShowtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_showcontent.c_my
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    private String cMy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_showcontent.c_id
     *
     * @return the value of t_showcontent.c_id
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_showcontent.c_id
     *
     * @param cId the value for t_showcontent.c_id
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public void setcId(String cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_showcontent.c_person
     *
     * @return the value of t_showcontent.c_person
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public String getcPerson() {
        return cPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_showcontent.c_person
     *
     * @param cPerson the value for t_showcontent.c_person
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public void setcPerson(String cPerson) {
        this.cPerson = cPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_showcontent.c_mz
     *
     * @return the value of t_showcontent.c_mz
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public String getcMz() {
        return cMz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_showcontent.c_mz
     *
     * @param cMz the value for t_showcontent.c_mz
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public void setcMz(String cMz) {
        this.cMz = cMz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_showcontent.d_showtime
     *
     * @return the value of t_showcontent.d_showtime
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public Date getdShowtime() {
        return dShowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_showcontent.d_showtime
     *
     * @param dShowtime the value for t_showcontent.d_showtime
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public void setdShowtime(Date dShowtime) {
        this.dShowtime = dShowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_showcontent.c_my
     *
     * @return the value of t_showcontent.c_my
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public String getcMy() {
        return cMy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_showcontent.c_my
     *
     * @param cMy the value for t_showcontent.c_my
     *
     * @mbggenerated Fri Sep 29 13:55:15 CST 2017
     */
    public void setcMy(String cMy) {
        this.cMy = cMy;
    }
}